In [1]:
import numpy as np

# 1 Newton-Raphson Einfach (eine Variable)

In [20]:
def f(x):
    return x**3-10
def df(x):
    return 3*x**2

#Startwert
x=10
#Iterationen
n=10

for i in range(n):
    x=x-(f(x)/df(x))
    print(f'n={i+1:<10}{x}')

n=1         6.7
n=2         4.540922254399644
n=3         3.188937050342083
n=4         2.453741355711228
n=5         2.189459564816151
n=6         2.154991996711556
n=7         2.154434834145626
n=8         2.154434690031893
n=9         2.154434690031884
n=10        2.154434690031884


# 2 Newton-Raphson Multivariable 

## 2.1 Vollständig

In [37]:
#6 Newton-Raphson Method - multivariable application

#x1 und x2 sind die Variabeln x und y
#Nimmt Spaltenvektor mit Shape(2,1) an und gibt auch einen zurück
def f(x):
    x1 = x[0,0]
    x2 = x[1,0]
    f1 = 4*x1**2 + x1*x2 - x2 -1
    f2 = 6*x2**2 - x1 - 2
    return np.array([[f1],[f2]])

#Jordanmatrix mit bereits vorbereiteten Derivatives
def j(x):
    x1 = x[0,0]
    x2 = x[1,0]
    xx11 = 8*x1+x2
    xx12 = x1-1
    xx21 = -1
    xx22 = 12*x2
    return np.array([[xx11,xx12],[xx21,xx22]])

#Anzahl Iterations n und Startwert x
n = 10
x = np.array([[1.0],[2.0]])

for i in range(n):
    #x = x - Jacobimatrix.inv @ f(x)
    #x ist Anfangs Startpunkt und nähert sich mit jeder Iteration dem Nullpunkt
    x -= np.linalg.inv(j(x)) @ f(x)
    print(f'n={i+1}\n{x}\n')

#Wichtig: Es gibt mehrere Resultate - NR findet jenes, das näher am Startwert liegt

n=1
[[0.7   ]
 [1.1125]]

n=2
[[0.59051603]
 [0.75029614]]

n=3
[[0.5677856 ]
 [0.66034497]]

n=4
[[0.56647262]
 [0.65405277]]

n=5
[[0.56646711]
 [0.6540218 ]]

n=6
[[0.56646711]
 [0.6540218 ]]

n=7
[[0.56646711]
 [0.6540218 ]]

n=8
[[0.56646711]
 [0.6540218 ]]

n=9
[[0.56646711]
 [0.6540218 ]]

n=10
[[0.56646711]
 [0.6540218 ]]



## 2.2 Vereinfacht (n=1 mit vorgerechneten Werten)

In [47]:
j1 = np.array([[10,0],
               [-1.0,24.0]])
f1 = np.array([[3.0],
               [21.0]])

#Startwerte
x = np.array([[1.0],
              [2.0]])

#x = x - inv(j1) @ f1
x -= np.linalg.inv(j1)@f1

print(x)
print(np.array([[1.0,2.0]]).T)

[[0.7   ]
 [1.1125]]
[[1.]
 [2.]]
